Added autodisable check for non helpers/mods (as per #55)
mojira/message-extension pull request #60
Opened 2021-05-15 14:07 UTC by bemoty

hi, i have created a working implementation for the requirement described in issue #55. 

my implementation disables the "Add Message" button if the extension notices that the currently logged in user is not a helper+. the disabled button looks like this:

![](https://i.bemoty.dev/MbySRL)
(the text "Sorry, you cannot use this here" is a tooltip)

the extension checks whether the button for updating / resolving the open issue is visible / exists. please do note that anyone could bypass this check simply by artificially adding an arbitrary HTML element to the `opsbar-opsbar-transitions` div so that the `document.querySelector('div#opsbar-opsbar-transitions').children.length > 0` check returns `true`. (even though it would probably be easier to just use the online version of the helper messages at this point lol)

if you have any feedback to my implementation please let me know. :)

hope this helps, cheers

2021-05-16 00:11 UTC, Pokechu22 commented
This seems like the right approach; it would also make sense if someone else has a JIRA instance that they want to use messages for, as someone who has the ability to transition issues would be in a situation where they would want to add comments when transitioning issues.  I haven't looked at the actual code though.

2021-06-10 21:43 UTC, violine1101 requested changes
Thank you for this, looks pretty good so far 👍

However, this does not disable adding a helper message via keyboard shortcut. I can still type `mji-dup` and the message appears. It only disables the dropdown.

Minor additional tweak suggestion, it would be nice if when hovering over the disabled "add message" button, the cursor would be changed to `not-allowed`, just to drive home the message, since the tooltip is way less noticeable on Windows than on your screenshot. Not a requirement though.

2021-06-13 12:12 UTC, bemoty commented
there you go :)

2021-06-16 22:08 UTC, violine1101 approved these changes
Thanks! Works great :)

2021-06-16 22:08 UTC, merged